openapi: 3.0.3
info:
  title: location filter service
  description: fetching filtered locations
  version: 1.0.0
paths:
  /locations:
    get:
      summary: lists all filtered locations
      description: list locations using search query and source lat/lng
      operationId: getLocations
      tags:
        - Locations
      parameters:
        - name: loc
          in: query
          description: lat/lng of source location
          required: false
          style: form
          explode: true
          schema:
            type: array
            minItems: 2
            maxItems: 2
            items:
              type: number
              format: double
            default: [0,0]
        - name: filter
          in: query
          description: pattern which will be used to search specific locations
          required: false
          schema:
            type: string
            default: ""
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                title: Location Response
                $ref: '#/components/schemas/LocationResponse'
        "400":
          description: Request is not correct
        "404":
          description: There is no endpoint found
        "500":
          description: Internal Server Error

components:
  schemas:
    LocationResponse:
      type: array
      items:
        $ref: '#/components/schemas/PlaceDTO'

    PlaceDTO:
      type: object
      properties:
        name:
          type: string
        address:
          type: object
          $ref: '#/components/schemas/AddressDTO'
        distance:
          type: number
          format: double
      required:
        - name
        - distance

    AddressDTO:
      type: object
      properties:
        street:
          type: string
        zipCode:
          type: string
        city:
          type: string
